config/routes.rb
Rails.application.routes.draw do
  root :to => 'bills#new'


  resources :sessions, :only => [:create, :destroy, :new]
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  
  resources :bills

  resources :users, :except => [:destroy, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord

    validates :name, :amount, presence: :true
  
    belongs_to :user
  
    has_many :guests, dependent: :destroy
  
    has_many :debts, dependent: :destroy
  
  
    def self.calculate(bill_id, bill_total, guests_params)
      guests_array = []
      
      guests_params.each do |guest|
        if guest.has_key?("money_to_pay")
            new_guest = Player.new(guest[:name], guest[:money_paid].to_f, guest[:money_to_pay].to_f)
            Guest.create(:name => guest[:name], :bill_id => bill_id, :money_paid => guest[:money_paid].to_f, :money_to_pay => guest[:money_to_pay].to_f)
        else
            money_to_pay = bill_total / guests_params.length.to_f
          new_guest = Player.new(guest[:name], guest[:money_paid].to_f, money_to_pay)
            Guest.create(:name => guest[:name], :bill_id => bill_id, :money_paid => guest[:money_paid].to_f, :money_to_pay => money_to_pay)
          end
        guests_array.push(new_guest)
      end
  
      guests_who_overpaid = []
      guests_who_underpaid = []
  
      guests_array.each do |guest|
        guests_who_overpaid.push(guest) if guest.bill_difference > 0
        guests_who_underpaid.push(guest) if guest.bill_difference < 0
      end
  
      debts_count = 0
  
      total_from_debtors = 0
  
      guests_who_underpaid.each do |guest|
        total_from_debtors += guest.amount_owes
      end
  
      guests_who_underpaid.each do |u_guest|
  
        guests_who_overpaid.each do |o_guest|
          owe_to_friend = u_guest.amount_owes * (o_guest.bill_difference/total_from_debtors.to_f)
          Debt.create(:bill_id => bill_id, :debtor_name => u_guest.name, :creditor_name => o_guest.name, :amount => owe_to_friend)
          debts_count += 1
        end
          end
  
          "#{debts_count} debts created for this bill."
      end
  
    def self.correct_input(bill_total, guests_params)
      guests_payment = 0
  
      guests_params.each do |guest|
        guests_payment += guest[:amount_paid].to_f
      end
  
      guests_payment == bill_total
    end
  
  end
  
  class Player
    attr_accessor :name, :money_paid, :money_to_pay, :id
  
    def initialize(name, money_paid, money_to_pay)
      @name = name
      @money_paid = money_paid
      @money_to_pay = money_to_pay
    end
  
    def bill_difference
      @money_paid - @money_to_pay
    end
  
    def amount_owes
      @money_to_pay - @money_paid
    end
  end
  

app/models/debt.rb
class Debt < ApplicationRecord

  belongs_to :bill

end

app/models/guest.rb
class Guest < ApplicationRecord

  belongs_to :bill

end

app/models/user.rb
class User < ApplicationRecord

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    has_secure_password

    has_many :bills

    has_many :debts, :foreign_key => "debtor_id"


    before_save { self.email = email.downcase }

    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    validates :name, :password, presence: :true
    validates :name, uniqueness: :true, allow_blank: :false

    def self.new_guest
        new { |u| u.guest = true }
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery

    
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  include ApplicationHelper, SessionsHelper

  def index
    @bills = current_user.bills
    render :index
  end

  def new
    @user = current_user
    @bill = Bill.new
  end

  def create
    bill_id = Bill.last.nil? ? 1 : Bill.last.id + 1
    @bill = Bill.new(:id => bill_id, :user => current_user, :name => params[:bill][:name], :description => params[:bill][:description], :amount => params[:bill][:amount])
    if @bill.valid?
      @bill.save

      print "###Bill Params"
      print params[:bill]

      params[:bill][:guests][0][:name] = current_user.name unless current_user.guest?
      Bill.calculate(bill_id,params[:bill][:amount].to_i, params[:bill][:guests])

      respond_to do |format|
				format.json { render :json => {:error => "none", :message => "Bill id: #{@bill.id} successfully added."} }
				format.html { redirect_to bill_url(@bill) }
			end
    else
        render :new
    end
  end

  def show
		@bill = Bill.find(params[:id])
		@guests = @bill.guests
		@debts = @bill.debts


		if current_user == @bill.user
			render :show
		else
			flash[:notice] = "Login required to edit bill."
			redirect_to login_url
		end
	end

  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: "Bill was successfully destroyed." }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include ApplicationHelper, SessionsHelper

  def new
    render :new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
		
		if @user && @user.authenticate(params[:user][:password])
			log_in(@user)	
      # byebug		
			flash[:notice] = "Successfully logged in."
			redirect_to user_url(@user)
		else
			flash.now[:danger] = 'Invalid email/password combination'
			render :new
		end
  end

  def destroy
    logout_user
		flash[:notice] = "Successful logout."
		redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper, SessionsHelper

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      flash[:success] = "Welcome to billsplit"
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def edit
  end

  def show
    # byebug
    @user = current_user
    @bills = @user.bills
    

  end

  def destroy
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include SessionsHelper

	def current_user
		if session[:user_id]
			@current_user ||= User.find_by(id: session[:user_id])
		# else
		# 	@current_user = User.new_guest
		# 	log_in(@current_user)
		end
	end

	def current_user?(user)
		user == current_user
	end

  	def require_login
		unless logged_in?
			flash[:danger] = "Please Log in"
			redirect_to login_url
		end
  	end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def logged_in?
		!current_user.nil?
	end

	def log_in(user)
		session[:user_id] = user[:id]
	end

	def logout_user
		if current_user
			session.delete(:user_id)
			current_user = nil
		end

		if session[:session_token]
			session[:session_token] = nil
		end
	end


	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bills/create.html.erb
<h1>Bills#create</h1>
<p>Find me in app/views/bills/create.html.erb</p>

app/views/bills/destroy.html.erb
<h1>Bills#destroy</h1>
<p>Find me in app/views/bills/destroy.html.erb</p>

app/views/bills/index.html.erb
<h1>Welcome</h1>
<%= button_to "Login", login_url %>
<%= button_to "Sign Up", '/users/new', method: :get%>

app/views/bills/new.html.erb
<h1 class="d-flex align-items-center justify-content-center">BillsPin	</h1>

<h4> <%= link_to "Profile", user_url(@user), class:"btn btn-outline-info" %> 
<h3>Add a Bill </h3>

<form   id="new-bill-form" action="<%= bills_url %>" method="post">
	
<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

	<div>
		<div class="col-3">
			<input class="form-control" type="text" id="bill-name" name="bill[name]" value="<%= @bill.name %>" placeholder="Bill Name">
		</div>
		<br>	
		<div class="col-3">
			<textarea class="form-control" id="bill-description" name="bill[description]" value="<%= @bill.description %>" placeholder="Bill Description (optional)" rows="2"></textarea>
		</div>
		<br>
		<div class="col-3">
			<input class="form-control" type="number" id="bill-amount" name="bill[amount]" value="<%= @bill.amount %>" placeholder="Amount">
		</div>
	</div>
	
	<br>
	

	<button class="btn btn-info" id="split-evenly">Split Evenly</button>

	
	<br>
	<br>
	<input type="hidden" name="bill[guests][][name]" ><span class="label label-success"> You </span> paid <input type="number" name="bill[guests][][money_paid]" class="amount-paid" placeholder="Amount">.
	<br>
	You are splitting this bill evenly with:
	<br>
	<br>
	<input type="text" class="guest-name" name="bill[guests][][name]" placeholder="Enter Friend Name"> paid <input type="number" name="bill[guests][][money_paid]" class="amount-paid" placeholder="Amount">
	<br>
	<br>
	<button class="btn btn-primary add-friend">Add Another Friend</button> or <input type="submit" class="btn btn-success" id="add-bill" value="Add Bill">
	<br>
	<div id="guests-on-bill"></div>
	<br>
</form>
    

<div id="form-submit-messages"></div>

app/views/bills/show.html.erb
<h2>Bill #<%= @bill.id %> Details</h2>
<br>
Created by: <%= @bill.user.name.nil? ? "Guest User" : @bill.user.name %> on <%= @bill.created_at.to_time.strftime('%B %e at %l:%M %p') %>
<br>
Bill Name: <%= @bill.name %>
<br>
<% unless @bill.description.blank? %>
	Bill Description: <%= @bill.description %>
<% end %>
<br>
Bill Amount: $<%= sprintf( "%0.02f", @bill.amount) %>
<br>
<br>
<br>
<h4>Bill Splitted as</h4>
<% @guests.each do |guest| %>
	<%= guest.name %> paid $<%= sprintf( "%0.02f", guest.money_paid) %>. <%= guest.name %> should have paid $<%= sprintf( "%0.02f", guest.money_to_pay) %>.
	<br>
<% end %>
<br>
<h4>Debt Details</h4>
<% @debts.each do |debt| %>
	<%= debt.debtor_name %> <%= debt.debtor_name == "You" ? "owe" : "owes" %> <%= debt.creditor_name == "You" ? "you" : debt.creditor_name %> $<%= sprintf( "%0.02f", debt.amount) %>.
	<br>
<% end %>
<br>
<br>
<div id="request-bill-confirmation">
	<input type="email" id="confirmation-email-address" placeholder="email@example.com"><button id="send-bill-confirmation" data-id=<%= @bill.id %> class="btn btn-primary"> Send Confirmation Email </button>
</div>
<br>
<br>
<div id="email-status">
</div>
<br>

<% if current_user.guest? %>
	<p><%= link_to "Create Account", new_user_url %> to save this bill.</p>
<% end %>

<p><%= link_to "Back to the index", root_url %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billsplit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar mb-2">
    <div class="container-fluid">
      <div class="navbar-header">
  
      </div>
      <% if current_user %>
        <ul class="nav navbar-right ">
          <li><%= link_to "Log out", logout_url, class: "mx-2" %></li> 
        </ul>
      <% else %>
        <ul class="nav navbar-right ">
          <li><%= link_to "Log in", login_url, class: "mx-2" %></li> 
          <li><%= link_to "Sign up", new_user_url, class: "mx-2" %></li>
        </ul>
      <% end %>
    </div>
  </nav>

  <%= yield %>

  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1 class='text-center'>Create Account</h1>

<div class="row">
  <div class="col-md-6 offset-3">
	<form id="new-account-form" action="<%= users_url %>" method="post">
		<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

		<input class="form-control" type="text" id="name" name="user[name]" value="<%= @user.name %>" placeholder="name"> 
		<br>
		<input class="form-control" type="text" id="email" name="user[email]" value="<%= @user.email %>" placeholder="email"> 
		<br>
		<input class="form-control" type="password" id="password" name="user[password]" placeholder="password"> 
		<br>
		<input type="submit" class="btn btn-success" value="Create Account">
	</form>
	<br>
	<p>Have an account already? <%= link_to "Login", login_url %></p> 
	<%= link_to "Back to Index", root_url %>
  </div>
  
</div>

app/views/users/show.html.erb
<h2>Hi <%= @user.name %>!</h2>
<br>
<h3> Bills Dashboard</h3>


<% if @bills.empty? %>
  <p>You have no bills.</p>
<% else %>
	<% @bills.each do |bill| %>
		<p>
			<b><%= bill.created_at.to_time.strftime('%B %e at %l:%M %p') %>:</b> Bill <%= bill.id %>
		  <%= link_to "#{ bill.name }", bill_url(bill) %> <%= link_to "Edit Bill #{bill.id}", edit_bill_url(bill), :class => "btn btn-warning" %> 
	  </p>
	<% end %>
<% end %>


<br>
<br>
<h3>Find Friends</h3>
<textarea>Input friend email</textarea>
<button class="btn btn-primary">Send Friend Request</button>

<p><%= link_to "Return to Index Page", root_url %></p>
<% if logged_in? %>
	<p><%= button_to "Log out", session_url, :method => "delete", class: "btn btn-danger" %></p>
<% end %>